# Generated by Django 2.1.3 on 2018-11-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xray', '0002_auto_20181128_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='xray',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='xray',
            name='result',
            field=models.TextField(blank=True),
        ),
    ]
