# Generated by Django 2.1.3 on 2018-11-29 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xray', '0005_auto_20181128_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xray',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
