# Generated by Django 2.1.3 on 2018-11-29 09:31

from django.db import migrations
import imagekit.models.fields
import xray.models


class Migration(migrations.Migration):

    dependencies = [
        ('xray', '0006_auto_20181129_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xray',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=xray.models.post_image_path),
        ),
    ]
